# NixOS Catppuccin Mocha wallpaper (3840x2160) from github.com/NixOS/nixos-artwork
wallpaper {
    monitor =
    path = ~/Pictures/wallpapers/qingbao.jpg
    fit_mode = cover
}

splash = false
ipc = true
