-- Auto-generated by init-monitors.sh on Hyprland start — do not edit by hand.
-- This file will be overwritten with your actual monitor layout on first boot.

-- Fallback: all connected displays get preferred mode, placed automatically.
hl.monitor({ output = "", mode = "preferred", position = "auto", scale = "auto" })

-- >>> hyprland-settings: monitors (do not edit this line)
-- <<< hyprland-settings: monitors (do not edit this line)
